language: python

dist: focal

matrix:
  include:
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64-graviton2
     virt: lxd
     group: edge

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --no-cache-dir -r requirements-test.txt

script:
  - make test
