language: python

dist: xenial

matrix:
  include:
   - os: linux
     arch: ppc64le
   - os: linux
     arch: s390x
   - os: linux
     arch: amd64
   - os: linux
     arch: arm64

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install --no-cache-dir -r requirements-test.txt

script:
  - make test
